# Generated by Django 3.1.1 on 2020-09-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('user_idx', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=13)),
                ('user_pwd', models.CharField(max_length=64)),
            ],
        ),
    ]
